### ISSUE TITLE
To find a restaurant

### ISSUE THREAD

**Issue by solyarepak** [OksanaSava/Informational-technologies#10]
your suggestions

**Comment by OksanaSava** [comment]
![image](https://user-images.githubusercontent.com/38244361/39180328-4603cba4-47bf-11e8-9e0c-ace6eab1dd2d.png)

**Comment by OksanaSava** [comment]
I like this one. What do you think

**Comment by solyarepak** [comment]
@OksanaSava great. let's choose this one
