### ISSUE TITLE
Found a musician

### ISSUE THREAD

**Issue by kyrylivv** [OksanaSava/Informational-technologies#11]
I would like to hear the songs of Oleg Vynnyk on the wedding

**Comment by kyrylivv** [comment]
![default](https://user-images.githubusercontent.com/38686312/39180041-8cda75ec-47be-11e8-8ade-4337f2a56200.png)

**Comment by OksanaSava** [comment]
I don't like him

**Comment by OksanaSava** [comment]
OMG

**Comment by solyarepak** [comment]
@kyrylivv You are a genius

**Comment by OksanaSava** [comment]
I love him after seeing this photo

**Comment by kyrylivv** [comment]
[Kobzar-Taras-Shevchenko-Ukr-Dnipro-1985.pdf](https://github.com/OksanaSava/Informational-technologies/files/1942215/Kobzar-Taras-Shevchenko-Ukr-Dnipro-1985.pdf)

**Comment by OksanaSava** [comment]
I made my decision. Let it be Vynnyk
