### ISSUE TITLE
List of guests

### ISSUE THREAD

**Issue by nadiazhyvan** [OksanaSava/Informational-technologies#8]
Let's think how many people should be

**Comment by OksanaSava** [comment]
I think approximately 100

**Comment by kyrylivv** [comment]
It is too many !At least 50

**Comment by nadiazhyvan** [comment]
![index](https://user-images.githubusercontent.com/38244334/39180089-ac33f27e-47be-11e8-85c5-7d8dff105864.png)

**Comment by nadiazhyvan** [comment]
[Wedding Guest List Template.pdf](https://github.com/OksanaSava/Informational-technologies/files/1942205/Wedding.Guest.List.Template.pdf)
@kyrylivv  watch this

**Comment by OksanaSava** [comment]
Have a nice wedding
