### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by OksanaSava** [OksanaSava/Informational-technologies#9]
I think we should have a lot of fish. What do you think

**Comment by kyrylivv** [comment]
No,there should be a lot of meat !!!

**Comment by OksanaSava** [comment]
![image](https://user-images.githubusercontent.com/38244361/39179904-347f7e4c-47be-11e8-9f8e-5e3e41d5b5bb.png)

**Comment by solyarepak** [comment]
https://www.telenews.pk/wp-content/uploads/2018/02/axomlive.jpg

**Comment by solyarepak** [comment]
![default](https://user-images.githubusercontent.com/38686498/39180119-c236c074-47be-11e8-97e3-2e571744e889.png)

**Comment by solyarepak** [comment]
the menu should look as the picture above @OksanaSava @kyrylivv @nadiazhyvan

**Comment by OksanaSava** [comment]
[HPM00796.pdf](https://github.com/OksanaSava/Informational-technologies/files/1942210/HPM00796.pdf)

**Comment by nadiazhyvan** [comment]
#7 it's too small for 50 person
